name: Release

on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: npm install
      - run: npm run make
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          path: out/make/zip/**/*.zip
      
